spring:
  jpa:
    database: postgresql
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
        id.new_generator_mappings: false
  liquibase:
    contexts: production
  datasource:
    url: jdbc:postgresql://rocket-shell.cclfgxid4oqr.sa-east-1.rds.amazonaws.com
    username: postgres
    password: Xw98QrKzZHfx5VgYCEor


server:
  port: 9002